name: Test Blossom Upload
on:
  push:
  pull_request:

jobs:
  test-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create test file
      run: |
        echo "This is a test file for Blossom upload" > test.txt
        echo "Test file created at: $(pwd)/test.txt"

    - name: Upload to Blossom
      uses: ./
      id: blossom-upload
      with:
        host: ${{ secrets.HOST }}
        filePath: test.txt
        nostrPrivateKey: ${{ secrets.NSEC }}

    - name: Show results
      run: |
        echo "Uploaded URL: ${{ steps.blossom-upload.outputs.blossomUrl }}"
        echo "File hash: ${{ steps.blossom-upload.outputs.blossomHash }}"
